/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistagraficaqytetet;

import java.util.ArrayList;

import modeloqytetet.Qytetet;
import controladorqytetet.*;

/**
 *
 * @author antonio
 */
public class VistaGraficaQytetet extends javax.swing.JFrame {

    /**
     * Creates new form VistaGraficaQytetet
     */
    public VistaGraficaQytetet() {
        ArrayList<String> nombres = obtenerNombreJugadores();
        
        modelo.inicializarJuego(nombres);
        
        initComponents();
        
        creaMenuOperacion();
        
        creaMenuCasilla();
        
        update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMensajes = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaMensajes = new javax.swing.JTextArea();
        panelJugadorActual = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaJugadorActual = new javax.swing.JTextArea();
        panelCartaActual = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaCartaActual = new javax.swing.JTextArea();
        panelTablero = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        areaTablero = new javax.swing.JTextArea();
        panelJugadores = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        areaJugadores = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        jMenuOperacion = new javax.swing.JMenu();
        jMenuCasilla = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Qytetet");

        areaMensajes.setColumns(20);
        areaMensajes.setRows(5);
        jScrollPane1.setViewportView(areaMensajes);

        panelMensajes.setViewportView(jScrollPane1);

        areaJugadorActual.setColumns(20);
        areaJugadorActual.setRows(5);
        jScrollPane2.setViewportView(areaJugadorActual);

        panelJugadorActual.setViewportView(jScrollPane2);

        areaCartaActual.setColumns(20);
        areaCartaActual.setRows(5);
        jScrollPane3.setViewportView(areaCartaActual);

        panelCartaActual.setViewportView(jScrollPane3);

        areaTablero.setColumns(20);
        areaTablero.setRows(5);
        jScrollPane4.setViewportView(areaTablero);

        panelTablero.setViewportView(jScrollPane4);

        panelJugadores.setToolTipText("");

        areaJugadores.setColumns(20);
        areaJugadores.setRows(5);
        jScrollPane5.setViewportView(areaJugadores);

        panelJugadores.setViewportView(jScrollPane5);

        jLabel1.setText("Jugadores");

        jLabel2.setText("Tablero");

        jLabel3.setText("Jugador actual");

        jLabel4.setText("Carta actual");

        jLabel5.setText("Mensajes");

        jMenuOperacion.setText("Menu Operacion");
        barraMenu.add(jMenuOperacion);

        jMenuCasilla.setText("Menu Casilla");
        barraMenu.add(jMenuCasilla);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(panelJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(12, 12, 12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(panelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGap(12, 12, 12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(panelJugadorActual, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(panelCartaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)))
                        .addComponent(panelMensajes, javax.swing.GroupLayout.PREFERRED_SIZE, 1285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelCartaActual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                            .addComponent(panelJugadorActual, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelTablero, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(4, 4, 4)
                .addComponent(panelMensajes, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaGraficaQytetet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaGraficaQytetet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaGraficaQytetet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaGraficaQytetet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaGraficaQytetet().setVisible(true);
            }
        });*/
        
        VistaGraficaQytetet vista = new VistaGraficaQytetet();
        
        vista.setVisible(true);
        
    }
    
    public void creaMenuOperacion(){
        for(OpcionMenu opcion: OpcionMenu.values()){
            javax.swing.JMenuItem itemOpcionMenu = new javax.swing.JMenuItem();
            
            itemOpcionMenu.setText(opcion.toString());
            itemOpcionMenu.setVisible(false);
            
            jMenuOperacion.add(itemOpcionMenu);
            
            
            itemOpcionMenu.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                 itemOpcionMenuActionPerformed(evt);
              }
            });
        }
            
            
    }
    
    
    public void creaMenuCasilla(){
        for(int i = 0; i < 20; i++){
            javax.swing.JMenuItem itemCasillaMenu = new javax.swing.JMenuItem();
            
            itemCasillaMenu.setText(Integer.toString(i));
            itemCasillaMenu.setVisible(false);
            
            jMenuCasilla.add(itemCasillaMenu);
            
            
            itemCasillaMenu.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                 itemCasillaMenuActionPerformed(evt);
              }
            });
        }
            
            
    }
    
    public void itemOpcionMenuActionPerformed(java.awt.event.ActionEvent evt){
        boolean encontrado = false;
        
        
        for(int i = 0; i < OpcionMenu.values().length && !encontrado; i++){
            if(OpcionMenu.values()[i].toString() == evt.getActionCommand()){
                encontrado = true;
                operacionElegida = i;
            }
        }
        
        if (controlador.necesitaElegirCasilla(operacionElegida)){
            updateJMenuCasillas(operacionElegida);
            areaMensajes.setText("\nNecesitas escoger una casilla\n");
            
        }else{
            areaMensajes.setText(controlador.realizarOperacion(operacionElegida, 0));
        }
        
        update();
    }
    
    public void itemCasillaMenuActionPerformed(java.awt.event.ActionEvent evt){
        int casilla;
        
        casilla = Integer.parseInt(evt.getActionCommand());
        
        areaMensajes.setText("\n Se va a " + OpcionMenu.values()[operacionElegida].toString() + 
                             " en la casilla " + casilla + "\n\n" + controlador.realizarOperacion(operacionElegida, casilla));

        
        update();

    }
    
    public void updateJMenuOperaciones(){
        ArrayList<Integer> operacionesValidas = controlador.obtenerOperacionesJuegoValidas();
        
        for(int i = 0; i < jMenuOperacion.getItemCount(); i++){   
            if(operacionesValidas.contains(i)){
                jMenuOperacion.getItem(i).setVisible(true);
            }else{
                jMenuOperacion.getItem(i).setVisible(false);
            }
            
        }
        
    }
    
    public void updateJMenuCasillas(int opcionMenu){
        ArrayList<Integer> operacionesValidas = controlador.obtenerCasillasValidas(opcionMenu);
        
        for(int i = 0; i < jMenuCasilla.getItemCount(); i++){   
            
            if(operacionesValidas.contains(i)){
                jMenuCasilla.getItem(i).setVisible(true);
            }else{
                jMenuCasilla.getItem(i).setVisible(false);
            }
            
        }
    }
    
    public void update(){
        areaJugadorActual.setText(modelo.getJugadorActual().toString());
        areaJugadores.setText(modelo.getJugadores().toString());
        
        if(modelo.getCartaActual() != null){
            areaCartaActual.setText(modelo.getCartaActual().toString());
        }else {
            areaCartaActual.setText("");
        }
        
        areaTablero.setText(modelo.getTablero().toString());
        
        updateJMenuOperaciones();
        //supongo que tengo que usar operacionElegida
        updateJMenuCasillas(operacionElegida);
        
        repaint();
    }
    
    public ArrayList<String> obtenerNombreJugadores(){
        DialogoNombres dialogo = new DialogoNombres(this, true);
        
        dialogo.setVisible(true);
        
        return dialogo.getNombres();
        
    }
    
    
    private Qytetet modelo = Qytetet.getInstance();
    private int operacionElegida;
    private ControladorQytetet controlador = ControladorQytetet.getInstance();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaCartaActual;
    private javax.swing.JTextArea areaJugadorActual;
    private javax.swing.JTextArea areaJugadores;
    private javax.swing.JTextArea areaMensajes;
    private javax.swing.JTextArea areaTablero;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenuCasilla;
    private javax.swing.JMenu jMenuOperacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane panelCartaActual;
    private javax.swing.JScrollPane panelJugadorActual;
    private javax.swing.JScrollPane panelJugadores;
    private javax.swing.JScrollPane panelMensajes;
    private javax.swing.JScrollPane panelTablero;
    // End of variables declaration//GEN-END:variables
}


//vender propiedad casas  a 0 ?

